### ISSUE TITLE
Is it possible to make the plugin running with GPU?

### ISSUE THREAD

**Issue by chuyaqifei** [fratopa/Mid360_simulation_plugin#2]
Mainly because raycasting bring too much computation overhead on CPU, is it possible to make the plugin running with GPU? It's crucial for multi-lidar simulation and multi-robot simulation.

**Comment by fratopa** [comment]
No with the current version of this plugin, I am currently working on a new version that will be GPU accelerated but is only going to support the mid-360 at first

**Comment by LihanChen2004** [comment]
> No with the current version of this plugin, I am currently working on a new version that will be GPU accelerated but is only going to support the mid-360 at first没有这个插件的当前版本，我目前正在开发一个新版本，该版本将进行 GPU 加速，但首先仅支持中型 360

Much thanks!!! I am also looking forward to the GPU version, and it would be even better if it could turn to ROS2 version.
