### ISSUE TITLE
How to link this plugin with PX4 simulation ?

### ISSUE THREAD

**Issue by SSZ1** [fratopa/Mid360_simulation_plugin#3]
I want to test a UAV  with PX4 SITL in Gazebo. And I want to add a mid360 on it. But when I build the PX4-Autopilot and your plugin. I couldn't add it to the iris.   So how could I link mid360 with iris in [PX4-Autopilot](https://github.com/PX4/PX4-Autopilot)?  The Compilation mode of PX4-Autopilot is very different.    Thanks a lot for your attention!

**Comment by fratopa** [comment]
Please paste here how you added the plugin to your iris model. I may have misunderstood what you are trying to do, but I had no problem adding this plugin to the sdf model of the Iris. 
Which version of gazebo are you using? this plugin does not support the newest gazebo ignition, it only works up to gazebo 11

**Comment by SSZ1** [comment]
Thanks for your kind reply. My gazebo version is 9 because my OS is ubuntu melodic. Here are my iris model code with adding mid360:
iris_livox_mid.sdf:

`<?xml version='1.0'?>
<sdf version='1.5'>
  <model name='iris_fpv_cam'>

    <include>
      <uri>model://iris</uri>
    </include>

    <include>
      <uri>model://kinect_self</uri>
      <pose>0.1 0 0 0 0 0</pose>
    </include>
    <joint name="kinect_self_joint" type="fixed">
      <child>kinect_self::link</child>
      <parent>iris::base_link</parent>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <upper>0</upper>
          <lower>0</lower>
        </limit>
      </axis>
    </joint>

    <include>
      <uri>model://livox_mid360</uri>
      <pose>0 0 0.1 0 0 0</pose>
    </include>
    <joint name="livox_mid360_joint" type="revolute">
      <child>livox_mid360::link</child>
      <parent>iris::base_link</parent>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <upper>0</upper>
          <lower>0</lower>
        </limit>
      </axis>
    </joint>

    <include>
      <uri>model://fpv_cam</uri>
      <pose>0 0 0 0 1.57 0</pose>
    </include>
    <joint name="fpv_cam_joint" type="fixed">
      <child>fpv_cam::link</child>
      <parent>iris::base_link</parent>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <upper>0</upper>
          <lower>0</lower>
        </limit>
      </axis>
    </joint>


  </model>
</sdf>
`

And  I created a livox_mid360 folder in the models of [PX4-Autopilot project](https://github.com/PX4/PX4-Autopilot) like this:
![image](https://github.com/fratopa/Mid360_simulation_plugin/assets/36888758/c6d30468-0d28-4ba3-9736-b8e573824ff2)

Here is the livox_mid360's code:

livox_mid360.sdf:

`<?xml version='1.0'?>
<sdf version="1.6">
  <model name="livox_mid360">
    
    <link name = "lidar_link">
      <pose>0.0 0.0 0.5 0.0 0.0 0.0</pose>
      <inertial>
        <mass>0.1</mass>
        <inertia>
          <ixx>0.0001</ixx>
          <ixy>0.0</ixy>
          <ixz>0.0</ixz>
          <iyy>0.0001</iyy>
          <iyz>0.0</iyz>
          <izz>0.0001</izz>
        </inertia>
      </inertial>
      <collision name = "lidar_collision">
        <geometry>
          <box>
            <size>0.05 0.05 0.05</size>
          </box>
        </geometry>
      </collision>
      <visual name = "lidar_visual">
        <geometry>
          <box>
            <size>0.05 0.05 0.05</size>
          </box>
        </geometry>
      </visual>

      <sensor type="ray" name="laser_livox">
        <pose>0 0 0.05 0 0 0</pose>
        <visualize>true</visualize>
        <always_on>True</always_on>
        <update_rate>10</update_rate>
        
        <plugin name="gazebo_ros_laser_controller" filename="liblivox_laser_simulation.so">
			  <ray>
			  <scan>
				  <horizontal>
				    <samples>100</samples>
				    <resolution>1</resolution>
				    <min_angle>-3.1415926535897931</min_angle>
            <max_angle>3.1415926535897931</max_angle>
				  </horizontal>
				  <vertical>
				    <samples>50</samples>
				    <resolution>1</resolution>
				    <min_angle>-3.1415926535897931</min_angle>
            <max_angle>3.1415926535897931</max_angle>
				  </vertical>
			  </scan>
			  <range>
				  <min>0.1</min>
				  <max>40</max>
				  <resolution>1</resolution>
			  </range>
			  <noise>
				  <type>gaussian</type>
				  <mean>0.0</mean>
				  <stddev>0.0</stddev>
			  </noise>
			  </ray>
          <visualize>True</visualize>
		      <samples>20000</samples>
		      <downsample>1</downsample>
		      <csv_file_name>mid360-real-centr.csv</csv_file_name>
          <publish_pointcloud_type>2</publish_pointcloud_type>
		      <ros_topic>/livox/lidar</ros_topic>
          <frameName>base_link</frameName>
        </plugin>
      </sensor>

    </link>




  </model>
</sdf>

`



And the launch file is like:

`<?xml version="1.0"?>
<launch>
    
    
    
    <arg name="x" default="0"/>
    <arg name="y" default="0"/>
    <arg name="z" default="0"/>
    <arg name="R" default="0"/>
    <arg name="P" default="0"/>
    <arg name="Y" default="0"/>
    
    <arg name="est" default="ekf2"/>
    
     <arg name="vehicle" default="iris"/>
    <arg name="my_model" default="iris_livox_mid"/>
    <arg name="world" default="$(find mavlink_sitl_gazebo)/worlds/empty.world"/>
    <arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/$(arg my_model)/$(arg my_model).sdf"/>

    
    <arg name="gui" default="true"/>
    <arg name="debug" default="false"/>
    <arg name="verbose" default="false"/>
    <arg name="paused" default="false"/>
    <arg name="respawn_gazebo" default="false"/>
    
    <arg name="fcu_url" default="udp://:14540@localhost:14557"/>
    <arg name="respawn_mavros" default="false"/>
    
    <arg name="interactive" default="true"/>
    
    <include file="$(find px4)/launch/posix_sitl.launch">
        <arg name="x" value="$(arg x)"/>
        <arg name="y" value="$(arg y)"/>
        <arg name="z" value="$(arg z)"/>
        <arg name="R" value="$(arg R)"/>
        <arg name="P" value="$(arg P)"/>
        <arg name="Y" value="$(arg Y)"/>
        <arg name="world" value="$(arg world)"/>
        <arg name="vehicle" value="$(arg vehicle)"/>
        <arg name="sdf" value="$(arg sdf)"/>
        <arg name="gui" value="$(arg gui)"/>
        <arg name="interactive" value="$(arg interactive)"/>
        <arg name="debug" value="$(arg debug)"/>
        <arg name="verbose" value="$(arg verbose)"/>
        <arg name="paused" value="$(arg paused)"/>
        <arg name="respawn_gazebo" value="$(arg respawn_gazebo)"/>
    </include>
    
    <include file="$(find mavros)/launch/px4.launch">
        
        <arg name="gcs_url" value=""/>
        <arg name="fcu_url" value="$(arg fcu_url)"/>
        <arg name="respawn_mavros" value="$(arg respawn_mavros)"/>
    </include>
</launch>
`



But when I run the launch file.  It showed nothing but:
![image](https://github.com/fratopa/Mid360_simulation_plugin/assets/36888758/0731455b-5394-4fad-b605-b5916dbfaa9e)

**Comment by SSZ1** [comment]
And I found a solution to add the mid360 plugin to iris.  That is I run two launch files in two project separately.   First, I run mavros_posix_sitl.launch   in  PX4-Autopilot project.  Then I run test_pattern.launch  in this project.    It could add the mid360 to iris.   It seems to work.  But there will be 2 gazebo windows like this:
![image](https://github.com/fratopa/Mid360_simulation_plugin/assets/36888758/fe208a35-7f7b-450a-9c5a-e1c862d214bd)

Why is this?   Thanks for your attention.

**Comment by SSZ1** [comment]
> And I found a solution to add the mid360 plugin to iris. That is I run two launch files in two project separately. First, I run mavros_posix_sitl.launch in PX4-Autopilot project. Then I run test_pattern.launch in this project. It could add the mid360 to iris. It seems to work. But there will be 2 gazebo windows like this: ![image](https://user-images.githubusercontent.com/36888758/260621833-fe208a35-7f7b-450a-9c5a-e1c862d214bd.png)
> 
> Why is this? Thanks for your attention.

there is a problem this way.  After I ran the two launch files separately.  I  changed the uav mode to offboard.   But the point clouds got stuck in rviz.  
![image](https://github.com/fratopa/Mid360_simulation_plugin/assets/36888758/3ad706d1-c20a-4f10-9e60-ca8ac8aed33c)

So how to fix this?

**Comment by fratopa** [comment]
Hi, I am sorry but I didn't had much time to dedicate to this project.

I don't have an easy way to test the setup on Melodic/Gazebo9. However looking at your most recent screenshots it looks like you might be encountering some hardware constraints problems. Your wall time is around 700 seconds while your ros elapsed time is less than 3 seconds, meaning your workstation is not able to render the pointcloud in real time. 


If this is the case i don't have any short term fixes, in the long term I aim to release a GPU accelerated version of this plugin. In the meantime you can increase the downsample factor to 2, this will half the number of points being computed
