### ISSUE TITLE
lidar points offset_time is error

### ISSUE THREAD

**Issue by zhouyixuan123** [fratopa/Mid360_simulation_plugin#4]
lidar points offset_time is error,max offset_time is only about 0.012474s,real lidar points max offset_time is about 0.100344s

**Comment by fratopa** [comment]
Hi, I think I fixed the bug but I consider that message format deprecated. If you need per-point timestamp I suggest you to use the updated default message format which is the only one I'll use from now on. 
Let me know if it works for you, i don't have any project to test the custom livox format on
